export const base_url = "https://localville.in/apis/admin_api/";
export const prod_url = "";

export const apis = {
    loginAdminData: "login_admin.php",
    addAdminData:"add_admin.php",
    getVendorsData:"get_vendors.php",
    getStoreData:"get_store.php",
    blockUser:"block_user.php",
    blockStore:"block_store.php",
    addCategory:"add_cat_section.php",
    getCategory:"get_cat_section.php",
    updateVendors:"update_vendors.php",
    getProducts:"get_products.php",
    updateProducts:"update_products.php",
    addProducts:"add_products.php",
    blockProducts:"block_products.php",
    updateStore:"update_store.php",
    addVendors:"add_vendors.php",
    addStore:"add_store.php",
    getDashboard:"dashboard.php",
    addPrdouctCategory:"add_prod_category.php",
    getProductCategory:"get_prod_categories.php",
    addProdSubCategory:"add_prod_subcategory.php",
    getProdSubCategory:"get_prod_subcategories.php",
    getUnverifiedProducts:"unverified_products.php",
    updateVerifiedProduct:"update_verified_products.php",
    getUnverifiedStore:"un_verif_stores.php",
    updateVerifiedStore:"update_unve_store.php",
    addSizeAttribute:"add_size_attribute.php",
    getSizeAttributes:"get_size_attributes.php",
    addSize:"add_size.php",
    addColor:"add_color.php",
    getColor:"get_color.php",
    getSize:"get_size.php",
    searchvendor:"search_vendor.php",
    searchproduct:"search_product.php",
    searchstore:"search_store.php"
}